# This subscription reacts on the topic `stoppedRecordingDiscord` and make the cooking server process
# the corresponding record.
# The `stoppedRecordingDiscord` event is fired by Pandora when it has successfully finished to record a voice channel
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: autocook
spec:
  topic: stoppedRecordingDiscord
  route: /
  pubsubname: pubsub
scopes:
  - cooking-server
