apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: object-store
spec:
  type: bindings.aws.s3
  version: v1
  metadata:
    - name: bucket
      value: recordings-test
    - name: region
      value: us-east-1
    - name: endpoint
      value: http://localhost:9000
    - name: forcePathStyle
      value: true
    - name: disableSSL
      value: true
    - name: encodeBase64
      value: true
    - name: decodeBase64
      value: true
    - name: accessKey
      value: "SjqeBIBwvLbtDj58"
    - name: secretKey
      value: "3vxGHkoskQM26KmMj2djm8XdxnwD8qUB"
